title: Kayal's World
description: Kayal's World
url: "https://kayalworld.com"
theme: minima
permalink: /:title

author:
  name: Kayal Imaya Kumar

plugins:
  - jekyll-feed
  - jekyll-sitemap

minima:
  skin: auto
  social_links:
    - platform: rss
      user_url: "https://kayalworld.com/feed.xml"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
